### PR TITLE
Allow for selected artboards to be exported to PDF

### PR DESCRIPTION
**Pull request by lifeofmle**
Added functionality to export selected artboards to PDF. Updated version number from 1.0 to 1.1

### CODE REVIEW

**Comment by sgraden** [comment]
This is a feature I have really wanted. Can this be integrated?

**Comment by fbmore** [comment]
BTW I combined the files from @lifeofmle and it's working great! Thanks! If anyone wants to download the plugin: https://www.dropbox.com/s/8rlt3awzfxbzh8z/sketch-artboards-to-pdf-master-FB.zip?dl=1

**Comment by fbmore** [comment]
@sgraden see my previous comment if you want to use the plugin!

**Comment by andrewfiorillo** [comment]
This was a great feature addition. It was implemented in another pull request, so I'm going to go ahead and close this.

**Pull request closed without merging**
